### ISSUE TITLE
[Feature request] Unity New Input System implementation

### ISSUE THREAD

**Issue by Racot007** [anarkila/DeveloperConsole#3]
It would be great to have support for the new input system  ^_^
( https://docs.unity3d.com/Packages/com.unity.inputsystem@1.3/manual/QuickStartGuide.html )

**Comment by anarkila** [comment]
I will consider this in the future, but for now I think I'm going to stick with the old Input system.

Migrating to the new Input system yourself shouldn't be that hard as all the inputs are handled by [ConsoleKeyInputs.cs](https://github.com/anarkila/DeveloperConsole/blob/main/Console/Assets/DeveloperConsole/Scripts/ConsoleKeyInputs.cs)  and all actions are event based. I will add documentation how to migrate to the Input system in next release.

**Comment by Racot007** [comment]
Thanks for doc
