### ISSUE TITLE
Console .prefab doesn't receive inputs in fresh scene

### ISSUE THREAD

**Issue by ndumais** [anarkila/DeveloperConsole#4]
When following the getting started instructions and adding the console to a new scene, the console will show but will seem frozen (doesn't accept any inputs or clicks). Also tried generating commands first in the new scene. Demo scene does work correctly though.

Exporting the prefab from the demo doesn't work either, so it seems like there might be a step missing?

**Edit: The scene needs to have an EventSystem and an InputModule for this to work.**

**Comment by anarkila** [comment]
Added EventSystem and InputModule to the prefab to fix this issue.
