### ISSUE TITLE
[Feature Request] Arrow Down to go back while previous command cycling

### ISSUE THREAD

**Issue by ndumais** [anarkila/DeveloperConsole#6]
Would allow to go back if you go past the command you were looking for, expected behaviour in command line.

**Comment by anarkila** [comment]
Added https://github.com/anarkila/DeveloperConsole/commit/55c9aab31bdd6877acd26aec1e3370129923e5a2. Commit is currently in the Dev branch.

**Comment by ndumais** [comment]
I think it's missing the part where it handles/checks for ArrowDown keypresses?

**Comment by ndumais** [comment]
![image](https://user-images.githubusercontent.com/48096495/204096181-820f2ac3-005f-454c-bf5d-1940cbbb4816.png)

It should be more like, "Console Search Command (Reverse) Key" or go back or something. Not sure if the issue is at the level of the feature too, but I think it might be?

Anyways, pressing arrow down, on my end, wont go back to the previous searched command.

**Comment by anarkila** [comment]
>Anyways, pressing arrow down, on my end, wont go back to the previous searched command.

Currently you have to first click Up Arrow and then you can use Down Arrow to go reverse direction. I believe this how Windows CMD and Linux terminal also does it.

This same key also fills from suggested commands if they are shown. So this key serves two purposes. I understand the naming is a bit odd. I'll try to find better naming for this.

**Comment by ndumais** [comment]
Ah okay, knowing that it makes more sense and mostly works. I don't mind the single key, but it seems that if you cycled previously and then autofill more than once, it will then also cycle afterwards which is a bit confusing, maybe splitting the keys or if autofill is used reset the check and only allow autofill?

**Comment by ndumais** [comment]
If there's both the check and the split keys, it could also allow to use Space for autofill, which I believe is pretty common in IDEs.
